# Generated by Django 6.0.5 on 2026-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='contact_number',
            field=models.CharField(default='Not Provided', max_length=20),
        ),
    ]
