# Generated by Django 6.0.5 on 2026-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bloodrequest_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='ambulance_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='ambulance_needed',
            field=models.BooleanField(default=False),
        ),
    ]
