# Generated by Django 6.0.5 on 2026-05-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bloodbankinventory_donor_last_donation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BloodCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('participants', models.ManyToManyField(blank=True, related_name='camps_joined', to='core.donor')),
            ],
        ),
    ]
